###
@baseUrl = http://localhost:3000

# @name getTaskbyId
GET {{baseUrl}}/tasks/2 HTTP/1.1
Content-Type: application/json
Authorization: Basic user2:password
###

# @name CreateTask
POST  {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Basic user2:password

{
    "title": "task from user2",
    "content": "content from user2"
}
###

# @name CreateUser
POST  {{baseUrl}}/users
Content-Type: application/json

{
    "username": "user2",
    "password": "password"
}
###
